sudo: false

language: node_js
node_js:
  - 6

before_install:
  - npm install codecov.io coveralls

script:
  - npm run test:coverage

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - test $TRAVIS_BRANCH = "master" &&
      npm run deploy

branches:
  only:
    - master

cache:
  directories:
  - node_modules # NPM packages
