sudo: false

language: node_js
node_js:
  - 6

before_install:
  - npm install codecov.io coveralls

script:
  - npm run test:coverage

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then npm run deploy

branches:
  only:
    - master
